config/routes.rb
Rails.application.routes.draw do
  resources :games

  root to: 'games#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
    has_many_attached :pieces_images
    has_one_attached :pdf_rules
    has_one_attached :cover_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy ]

  # GET /games or /games.json
  def index
    @games = Game.with_attached_pieces_images.all
    
  end

  # GET /games/1 or /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games or /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: "Game was successfully created." }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: "Game was successfully updated." }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: "Game was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:name, :rules, :cover_image, :pdf_rules, pieces_images: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>  
  
  <div class="field">
    <%= form.label :rules %>
    <%= form.text_field :rules %>
  </div>
  
  <div class="field">
    <%= form.label :cover_image %>
    <%= form.file_field :cover_image , direct_upload: true %>
  </div>  

    <div class="field">
    <%= form.label :pieces_images %>
    <%= form.file_field :pieces_images, multiple: true, direct_upload: true %>
  </div>

   <div class="field">
    <%= form.label :pdf_rules %>
    <%= form.file_field :pdf_rules, direct_upload: true %>
  </div>  


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table class="table table-bordered  border-dark">
  <thead>
    <tr>
      <th>Game</th>
      <th>Rules</th>
      <th>cover</th>
      <th>Pieces</th>
      <th>Pdf</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class=''>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= game.rules %></td>
        <% if game.cover_image.attached? %>
          <td>
            <%= link_to rails_blob_path(game.cover_image, disposition:'attachment') do %>
              <%= image_tag game.cover_image.variant(resize: "100x100",type: :grayscale ) %>
            <% end %>
          </td>
        <% end %>
        <% if game.pieces_images.attached? %>
          <td>
            <% game.pieces_images.each do |img| %>
              <%= link_to rails_blob_path(img, disposition:'attachment') do %>
                <%= image_tag img.variant(resize: "100x100",type: :grayscale ) %>
              <% end %>
            <% end %>
           </td> 
        <% end %>
        <% if game.pdf_rules.attached? %>
          <td><%= link_to 'Dowload Pdf', rails_blob_path(game.pdf_rules, disposition:'attachment') %></td>
        <% end %>
        <td ><%= link_to 'Show', game %></td>
        <td ><%= link_to 'Edit', edit_game_path(game) %></td>
        <td ><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppGames</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">  
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>